server:
  port: 10000

spring:
  datasource:
    druid:
      one:
        url: jdbc:mysql://10.157.163.47:3306/one?useUnicode=true&characterEncoding=utf-8
        username: root
        password: hd123
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filter: stat,slf4j
        initialSize: 10
        minIdle: 10
        maxActive: 1000
        #验证连接的有效性
        testOnBorrow: true
        #获取连接时候验证，会影响性能
        testWhileIdle: true
        validationQuery: SELECT 1
        #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
        timeBetweenEvictionRunsMillis: 300000
        #连接池空闲连接的有效时间 ，设置30分钟
        minEvictableIdleTimeMillis: 1800000
      two:
        url: jdbc:mysql://10.157.163.47:3306/two?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
        username: root
        password: hd123
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 1000
        #验证连接的有效性
        testOnBorrow: true
        #获取连接时候验证，会影响性能
        testWhileIdle: true
        validationQuery: SELECT 1
        #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
        timeBetweenEvictionRunsMillis: 300000
        #连接池空闲连接的有效时间 ，设置30分钟
        minEvictableIdleTimeMillis: 1800000
